### ISSUE TITLE
生成key的网址不可用，以及deploy后域名被分配的是内网IP

### ISSUE THREAD

**Issue by liziqing** [aws-samples/serverless-woocommerce-workshop#9]
https://keys.live.lambdashop.xyz/ 失效，只能手动openssl生成48位的key

另外按照工作坊的步骤deploy顺利完成后，打开域名，显示无法访问，ping域名后发现解析的是aws的内网ip，是哪里步骤有误？

**Comment by bnusunny** [comment]
感谢，我们会处理域名过期的问题。

你部署后，网站的域名服务器是否更新？ 你可以用下面的命令看看。

dig <your domain> NS

**Comment by liziqing** [comment]
部署后再更新ns？是之前就托管给route53，而且www域名也自动添加的，但指向的分配的clountfront.net子域名解析出来就是内网IP

**Comment by bnusunny** [comment]
你的域名是？

**Comment by bnusunny** [comment]
https://keys.live.lambdashop.xyz/ 已经恢复。

**Comment by liziqing** [comment]
> 你的域名是？

你看下A记录指向的 d39m5078lwjkk3.cloudfront.net.

**Comment by liziqing** [comment]
NS记录
asandaigou.com.         86400   IN      NS      ns-733.awsdns-27.net.
asandaigou.com.         86400   IN      NS      ns-114.awsdns-14.com.
asandaigou.com.         86400   IN      NS      ns-1501.awsdns-59.org.
asandaigou.com.         86400   IN      NS      ns-1795.awsdns-32.co.uk.

**Comment by bnusunny** [comment]
A记录没问题。访问https://www.asandaigou.com/,  显示WordPress的安装页面。

```
C:\Users\zhang>nslookup d39m5078lwjkk3.cloudfront.net
服务器:  cq.ctcdma.com
Address:  61.128.128.68

非权威应答:
名称:    d39m5078lwjkk3.cloudfront.net
Addresses:  2600:9000:2250:ca00:c:5470:b4c0:93a1
          2600:9000:2250:6800:c:5470:b4c0:93a1
          2600:9000:2250:3800:c:5470:b4c0:93a1
          2600:9000:2250:8600:c:5470:b4c0:93a1
          2600:9000:2250:7a00:c:5470:b4c0:93a1
          2600:9000:2250:2800:c:5470:b4c0:93a1
          2600:9000:2250:9e00:c:5470:b4c0:93a1
          2600:9000:2250:dc00:c:5470:b4c0:93a1
          18.66.122.46
          18.66.122.18
          18.66.122.74
          18.66.122.124

```
